# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "bootstrap-4.2.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.2.1.tgz";
        sha512 = "tt/7vIv3Gm2mnd/WeDx36nfGGHleil0Wg8IeB7eMrVkY0fZ5iTaBisSh8oNANc2IBsCc6vCgCNTIM/IEN0+50Q==";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "cache-polyfill-1.0.1" = {
      name = "cache-polyfill";
      packageName = "cache-polyfill";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-polyfill/-/cache-polyfill-1.0.1.tgz";
        sha512 = "bIMkvMYuXvOOUMoxUChREYXT6OZi4kvPcRQrmEyaPkLR21sLwDfhdhxxSifZmoiPGQHNEdbeuVNtO5oXbSP31Q==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "dexie-2.0.4" = {
      name = "dexie";
      packageName = "dexie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dexie/-/dexie-2.0.4.tgz";
        sha512 = "aQ/s1U2wHxwBKRrt2Z/mwFNHMQWhESerFsMYzE+5P5OsIe5o1kgpFMWkzKTtkvkyyEni6mWr/T4HUJuY9xIHLA==";
      };
    };
    "event-target-shim-3.0.2" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-3.0.2.tgz";
        sha512 = "HK5GhnEAkm7fLy249GtF7DIuYmjLm85Ft6ssj7DhVl8Tx/z9+v0W6aiIVUdT4AXWGYy5Fc+s6gqBI49Bf0LejQ==";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "history-4.7.2" = {
      name = "history";
      packageName = "history";
      version = "4.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-4.7.2.tgz";
        sha512 = "1zkBRWW6XweO0NBcjiphtVJVsIQ+SXF29z9DVkceeaSLVMFXHool+fdCZD4spDCfZJCILPILc3bm7Bc+HRi0nA==";
      };
    };
    "hoist-non-react-statics-2.5.5" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "2.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-2.5.5.tgz";
        sha512 = "rqcy4pJo55FTTLWt+bU8ukscqHeE/e9KWvsOW2b/a3afxQZhwkQdT1rPPCJ0rYXdj4vNcasY8zHTH+jF/qStxw==";
      };
    };
    "hoist-non-react-statics-3.3.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.0.tgz";
        sha512 = "0XsbTXxgiaCDYDIWFcwkmerZPSwywfUqYmwT4jzewKTQSWoE6FCMoUVOeBJWK3E/CrWbxRG3m5GzY4lnIwGRBA==";
      };
    };
    "http-parser-js-0.4.13" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.13.tgz";
        sha1 = "3bd6d6fde6e3172c9334c3b33b6c193d80fe1137";
      };
    };
    "ieee754-1.1.12" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.12.tgz";
        sha512 = "GguP+DRY+pJ3soyIiGPTvdiVXjZ+DbXOxGpXn3eMvNW4x4irjqXm4wHKscC+TfxSJ0yw/S1F24tqdMNsMZTiLA==";
      };
    };
    "immutable-3.8.2" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.8.2.tgz";
        sha1 = "c2439951455bb39913daf281376f1530e104adf3";
      };
    };
    "intrustd-git://github.com/intrustd/js" = {
      name = "intrustd";
      packageName = "intrustd";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/intrustd/js";
        rev = "85178f0f37327d9d3fe52fab39683daa74d97045";
        sha256 = "42ac7e269f03119924e4a10bd4f8da45e0441fb7f2589541c4a867835592ebf8";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "jquery-3.3.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz";
        sha512 = "Ubldcmxp5np52/ENotGxlLe6aGMvmF4R8S6tZjsP6Knsaxd/xp3Zrh50cG93lR6nPXyUFwzN3ZSOQI0wRJNdGg==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "lodash-4.17.11" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz";
        sha512 = "cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "mithril-1.1.6" = {
      name = "mithril";
      packageName = "mithril";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mithril/-/mithril-1.1.6.tgz";
        sha512 = "fWcUrQTCqu8M916rj1MFGlHaPh65rznPu6U/N2U9g81H89klDCIptSK5bnkNkC+jyi3sJIXjyGhSQjUnR8jzZA==";
      };
    };
    "nprogress-0.2.0" = {
      name = "nprogress";
      packageName = "nprogress";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nprogress/-/nprogress-0.2.0.tgz";
        sha1 = "cb8f34c53213d895723fcbab907e9422adbcafb1";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "path-to-regexp-1.7.0" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-1.7.0.tgz";
        sha1 = "59fde0f435badacba103a84e9d3bc64e96b9937d";
      };
    };
    "popper.js-1.14.7" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.14.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.14.7.tgz";
        sha512 = "4q1hNvoUre/8srWsH7hnoSJ5xVmIL4qgz+s4qf2TnJIMyZFUFMGH+9vE7mXynAlHSZ/NdTmmow86muD0myUkVQ==";
      };
    };
    "prop-types-15.6.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.6.2.tgz";
        sha512 = "3pboPvLiWD7dkI3qf3KbUe6hKFKa52w+AE0VCqECtf+QHAKgOL37tTaNCnuX1nAAQ4ZhyP+kYVKf8rLmJ/feDQ==";
      };
    };
    "query-string-6.2.0" = {
      name = "query-string";
      packageName = "query-string";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-6.2.0.tgz";
        sha512 = "5wupExkIt8RYL4h/FE+WTg3JHk62e6fFPWtAZA9J5IWK1PfTfKkMS93HBUHcFpeYi9KsY5pFbh+ldvEyaz5MyA==";
      };
    };
    "react-16.7.0" = {
      name = "react";
      packageName = "react";
      version = "16.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.7.0.tgz";
        sha512 = "StCz3QY8lxTb5cl2HJxjwLFOXPIFQp+p+hxQfc8WE0QiLfCtIlKj8/+5tjjKm8uSTlAW+fCPaavGFS06V9Ar3A==";
      };
    };
    "react-dom-16.7.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.7.0.tgz";
        sha512 = "D0Ufv1ExCAmF38P2Uh1lwpminZFRXEINJe53zRAbm4KPwSyd6DY/uDoS0Blj9jvPpn1+wivKpZYc8aAAN/nAkg==";
      };
    };
    "react-is-16.7.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.7.0.tgz";
        sha512 = "Z0VRQdF4NPDoI0tsXVMLkJLiwEBa+RP66g0xDHxgxysxSoCUccSten4RTF/UFvZF1dZvZ9Zu1sx+MDXwcOR34g==";
      };
    };
    "react-mentions-2.4.1" = {
      name = "react-mentions";
      packageName = "react-mentions";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-mentions/-/react-mentions-2.4.1.tgz";
        sha512 = "irw5V5IJ5NU+Lr1QVgQd8395gh3Lyrgz9/Uhyp6S2aDR4X4E2gz0Hf4saLvk+bBDJpNmV/j+oJsn28Me0rPIqg==";
      };
    };
    "react-photo-gallery-6.3.1" = {
      name = "react-photo-gallery";
      packageName = "react-photo-gallery";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-photo-gallery/-/react-photo-gallery-6.3.1.tgz";
        sha512 = "PJOvCXVoO8fgP9n6yOcZ3TfqiND5EliDclmBYvuDjjenvkhLu8C/a7w8kdVT0XviWElAJrQIm9kBU8hRqoP05g==";
      };
    };
    "react-router-4.3.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-4.3.1.tgz";
        sha512 = "yrvL8AogDh2X42Dt9iknk4wF4V8bWREPirFfS9gLU1huk6qK41sg7Z/1S81jjTrGHxa3B8R3J6xIkDAA6CVarg==";
      };
    };
    "react-router-dom-4.3.1" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-4.3.1.tgz";
        sha512 = "c/MlywfxDdCp7EnB7YfPMOfMD3tOtIjrQlj/CKfNMBxdmpJP8xcz5P/UAFn3JbnQCNUxsHyVVqllF9LhgVyFCA==";
      };
    };
    "react-visibility-sensor-5.0.2" = {
      name = "react-visibility-sensor";
      packageName = "react-visibility-sensor";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-visibility-sensor/-/react-visibility-sensor-5.0.2.tgz";
        sha512 = "7+1lr7oQOO2vKr5u/uxoDGFWAAy7lsDy2aJU3Zy1/OymI+TRqOBk8m2L8YE1B0UyfCDWxVAWO+aifVGqNOvqeQ==";
      };
    };
    "resize-observer-polyfill-1.5.1" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.1.tgz";
        sha512 = "LwZrotdHOo12nQuZlHEmtuXdqGoOD0OhaxopaNFxWzInpEgaLWoVuAMbTzixuosCx2nEG58ngzW3vxdWoxIgdg==";
      };
    };
    "resolve-pathname-2.2.0" = {
      name = "resolve-pathname";
      packageName = "resolve-pathname";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pathname/-/resolve-pathname-2.2.0.tgz";
        sha512 = "bAFz9ld18RzJfddgrO2e/0S2O81710++chRMUxHjXOYKF6jTAMrUNZrEZ1PvV0zlhfjidm08iRPdTLPno1FuRg==";
      };
    };
    "scheduler-0.12.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.12.0.tgz";
        sha512 = "t7MBR28Akcp4Jm+QoR63XgAi9YgCUmgvDHqf5otgAj4QvdoBE4ImCX0ffehefePPG+aitiYHp0g/mW6s4Tp+dw==";
      };
    };
    "strict-uri-encode-2.0.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-2.0.0.tgz";
        sha1 = "b9c7330c7042862f6b142dc274bbcc5866ce3546";
      };
    };
    "substyle-6.3.1" = {
      name = "substyle";
      packageName = "substyle";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/substyle/-/substyle-6.3.1.tgz";
        sha512 = "S25YRgVQB25cLXgGAJ7AXTYewkIB/9Fa1Y7jxkN48U4N6rbK9YhVEiF7vtPGLlJl8ebSOJ3N4t8cd6jL8MH7Uw==";
      };
    };
    "uikit-3.0.3" = {
      name = "uikit";
      packageName = "uikit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uikit/-/uikit-3.0.3.tgz";
        sha512 = "Z73TXlnfJCAXczg5mFCZSTwR0Ii1wW2fZumfIR8G1x1x4SyKHpkU0JCZDoIryYFMu1gSpvy5hZiXk3t4i5tTlw==";
      };
    };
    "underscore-1.9.1" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz";
        sha512 = "5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==";
      };
    };
    "utf8-3.0.0" = {
      name = "utf8";
      packageName = "utf8";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8/-/utf8-3.0.0.tgz";
        sha512 = "E8VjFIQ/TyQgp+TZfS6l8yp/xWppSAHzidGiRrqe4bK4XP9pTRyKFgGJpO3SN7zdX4DeomTrwaseCHovfpFcqQ==";
      };
    };
    "value-equal-0.4.0" = {
      name = "value-equal";
      packageName = "value-equal";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-equal/-/value-equal-0.4.0.tgz";
        sha512 = "x+cYdNnaA3CxvMaTX0INdTCN8m8aF2uY9BvEqmxuYp8bL09cs/kWVQPVGcA35fMktdOsP69IgU7wFj/61dJHEw==";
      };
    };
    "vcard-parser-1.0.0" = {
      name = "vcard-parser";
      packageName = "vcard-parser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vcard-parser/-/vcard-parser-1.0.0.tgz";
        sha512 = "rSEjrjBK3of4VimMR5vBjLLcN5ZCSp9yuVzyx5i4Fwx74Yd0s+DnHtSit/wAAtj1a7/T/qQc0ykwXADoD0+fTQ==";
      };
    };
    "warning-2.1.0" = {
      name = "warning";
      packageName = "warning";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-2.1.0.tgz";
        sha1 = "21220d9c63afc77a8c92111e011af705ce0c6901";
      };
    };
    "warning-3.0.0" = {
      name = "warning";
      packageName = "warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-3.0.0.tgz";
        sha1 = "32e5377cb572de4ab04753bdf8821c01ed605b7c";
      };
    };
    "warning-4.0.2" = {
      name = "warning";
      packageName = "warning";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-4.0.2.tgz";
        sha512 = "wbTp09q/9C+jJn4KKJfJfoS6VleK/Dti0yqWSm6KMvJ4MRCXFQNapHuJXutJIrWV0Cf4AhTdeIe4qdKHR1+Hug==";
      };
    };
    "web-streams-polyfill-1.3.2" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-1.3.2.tgz";
        sha1 = "3719245e909282d93967825f44bcd550e9c03995";
      };
    };
    "webpack-merge-4.2.1" = {
      name = "webpack-merge";
      packageName = "webpack-merge";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-merge/-/webpack-merge-4.2.1.tgz";
        sha512 = "4p8WQyS98bUJcCvFMbdGZyZmsKuWjWVnVHnAS3FFg0HDaRVrPbkivx2RYCre8UiemD67RsiFFLfn4JhLAin8Vw==";
      };
    };
  };
  args = {
    name = "intrustd-photo-app";
    packageName = "intrustd-photo-app";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."base64-js-1.3.0"
      sources."bootstrap-4.2.1"
      sources."buffer-5.2.1"
      sources."cache-polyfill-1.0.1"
      sources."decode-uri-component-0.2.0"
      sources."dexie-2.0.4"
      sources."event-target-shim-3.0.2"
      sources."font-awesome-4.7.0"
      (sources."history-4.7.2" // {
        dependencies = [
          sources."warning-3.0.0"
        ];
      })
      sources."hoist-non-react-statics-3.3.0"
      sources."http-parser-js-0.4.13"
      sources."ieee754-1.1.12"
      sources."immutable-3.8.2"
      sources."intrustd-git://github.com/intrustd/js"
      sources."invariant-2.2.4"
      sources."isarray-0.0.1"
      sources."jquery-3.3.1"
      sources."js-tokens-4.0.0"
      sources."lodash-4.17.11"
      sources."loose-envify-1.4.0"
      sources."mithril-1.1.6"
      sources."nprogress-0.2.0"
      sources."object-assign-4.1.1"
      sources."path-to-regexp-1.7.0"
      sources."popper.js-1.14.7"
      sources."prop-types-15.6.2"
      sources."query-string-6.2.0"
      sources."react-16.7.0"
      sources."react-dom-16.7.0"
      sources."react-is-16.7.0"
      sources."react-mentions-2.4.1"
      sources."react-photo-gallery-6.3.1"
      (sources."react-router-4.3.1" // {
        dependencies = [
          sources."hoist-non-react-statics-2.5.5"
          sources."warning-4.0.2"
        ];
      })
      (sources."react-router-dom-4.3.1" // {
        dependencies = [
          sources."warning-4.0.2"
        ];
      })
      sources."react-visibility-sensor-5.0.2"
      sources."resize-observer-polyfill-1.5.1"
      sources."resolve-pathname-2.2.0"
      sources."scheduler-0.12.0"
      sources."strict-uri-encode-2.0.0"
      sources."substyle-6.3.1"
      sources."uikit-3.0.3"
      sources."underscore-1.9.1"
      sources."utf8-3.0.0"
      sources."value-equal-0.4.0"
      sources."vcard-parser-1.0.0"
      sources."warning-2.1.0"
      sources."web-streams-polyfill-1.3.2"
      sources."webpack-merge-4.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The default Photos application that ships with intrustd";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}