# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.5.4" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.5.4.tgz";
        sha512 = "Na84uwyImZZc3FKf4aUF1tysApzwf3p2yuFBIyBfbzT5glzKTdvYI4KVW4kcgjrzoGUjC7w3YyCHcJKaRxsr2Q==";
      };
    };
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "bootstrap-4.3.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.3.1.tgz";
        sha512 = "rXqOmH1VilAt2DyPzluTi2blhk17bO7ef+zLLPlWvG494pDxcM234pJ8wTc/6R40UWizAIIMgxjvxZg5kmsbag==";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "cache-polyfill-1.0.1" = {
      name = "cache-polyfill";
      packageName = "cache-polyfill";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-polyfill/-/cache-polyfill-1.0.1.tgz";
        sha512 = "bIMkvMYuXvOOUMoxUChREYXT6OZi4kvPcRQrmEyaPkLR21sLwDfhdhxxSifZmoiPGQHNEdbeuVNtO5oXbSP31Q==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "dexie-2.0.4" = {
      name = "dexie";
      packageName = "dexie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dexie/-/dexie-2.0.4.tgz";
        sha512 = "aQ/s1U2wHxwBKRrt2Z/mwFNHMQWhESerFsMYzE+5P5OsIe5o1kgpFMWkzKTtkvkyyEni6mWr/T4HUJuY9xIHLA==";
      };
    };
    "event-target-shim-3.0.2" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-3.0.2.tgz";
        sha512 = "HK5GhnEAkm7fLy249GtF7DIuYmjLm85Ft6ssj7DhVl8Tx/z9+v0W6aiIVUdT4AXWGYy5Fc+s6gqBI49Bf0LejQ==";
      };
    };
    "eventemitter3-3.1.0" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.0.tgz";
        sha512 = "ivIvhpq/Y0uSjcHDcOIccjmYjGLcP09MFGE7ysAwkAvkXfpZlC985pH2/ui64DKazbTW/4kN3yqozUxlXzI6cA==";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "history-4.9.0" = {
      name = "history";
      packageName = "history";
      version = "4.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-4.9.0.tgz";
        sha512 = "H2DkjCjXf0Op9OAr6nJ56fcRkTSNrUiv41vNJ6IswJjif6wlpZK0BTfFbi7qK9dXLSYZxkq5lBsj3vUjlYBYZA==";
      };
    };
    "hls.js-0.12.4" = {
      name = "hls.js";
      packageName = "hls.js";
      version = "0.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hls.js/-/hls.js-0.12.4.tgz";
        sha512 = "e8OPxQ60dBVsdkv4atdxR21KzC1mgwspM41qpozpj3Uv1Fz4CaeQy3FWoaV2O+QKKbNRvV5hW+/LipCWdrwnMQ==";
      };
    };
    "hoist-non-react-statics-2.5.5" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "2.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-2.5.5.tgz";
        sha512 = "rqcy4pJo55FTTLWt+bU8ukscqHeE/e9KWvsOW2b/a3afxQZhwkQdT1rPPCJ0rYXdj4vNcasY8zHTH+jF/qStxw==";
      };
    };
    "hoist-non-react-statics-3.3.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.0.tgz";
        sha512 = "0XsbTXxgiaCDYDIWFcwkmerZPSwywfUqYmwT4jzewKTQSWoE6FCMoUVOeBJWK3E/CrWbxRG3m5GzY4lnIwGRBA==";
      };
    };
    "http-parser-js-0.4.13" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.13.tgz";
        sha1 = "3bd6d6fde6e3172c9334c3b33b6c193d80fe1137";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "immutable-3.8.2" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.8.2.tgz";
        sha1 = "c2439951455bb39913daf281376f1530e104adf3";
      };
    };
    "intrustd-git://github.com/intrustd/js" = {
      name = "intrustd";
      packageName = "intrustd";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/intrustd/js";
        rev = "271f10177dc931ad5d7d607c2ad1e3698ba6046c";
        sha256 = "cdaf1bad1067f45f6edb7199b43e723964f9f47d7cb953ca5ed39b01a179fc72";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "jquery-3.4.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz";
        sha512 = "36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "lodash-4.17.14" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.14.tgz";
        sha512 = "mmKYbW3GLuJeX+iGP+Y7Gp1AiGHGbXHCOh/jZmrawMmsE7MS4znI3RL2FsjbqOyMayHInjOeykW7PEajUk1/xw==";
      };
    };
    "lodash-es-4.17.14" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.14.tgz";
        sha512 = "7zchRrGa8UZXjD/4ivUWP1867jDkhzTG2c/uj739utSd7O/pFFdxspCemIFKEEjErbcqRzn8nKnGsi7mvTgRPA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "mithril-1.1.6" = {
      name = "mithril";
      packageName = "mithril";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mithril/-/mithril-1.1.6.tgz";
        sha512 = "fWcUrQTCqu8M916rj1MFGlHaPh65rznPu6U/N2U9g81H89klDCIptSK5bnkNkC+jyi3sJIXjyGhSQjUnR8jzZA==";
      };
    };
    "nprogress-0.2.0" = {
      name = "nprogress";
      packageName = "nprogress";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nprogress/-/nprogress-0.2.0.tgz";
        sha1 = "cb8f34c53213d895723fcbab907e9422adbcafb1";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "path-to-regexp-1.7.0" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-1.7.0.tgz";
        sha1 = "59fde0f435badacba103a84e9d3bc64e96b9937d";
      };
    };
    "popper.js-1.15.0" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.15.0.tgz";
        sha512 = "w010cY1oCUmI+9KwwlWki+r5jxKfTFDVoadl7MSrIujHU5MJ5OR6HTDj6Xo8aoR/QsA56x8jKjA59qGH4ELtrA==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "query-string-6.8.1" = {
      name = "query-string";
      packageName = "query-string";
      version = "6.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-6.8.1.tgz";
        sha512 = "g6y0Lbq10a5pPQpjlFuojfMfV1Pd2Jw9h75ypiYPPia3Gcq2rgkKiIwbkS6JxH7c5f5u/B/sB+d13PU+g1eu4Q==";
      };
    };
    "raf-schd-4.0.2" = {
      name = "raf-schd";
      packageName = "raf-schd";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raf-schd/-/raf-schd-4.0.2.tgz";
        sha512 = "VhlMZmGy6A6hrkJWHLNTGl5gtgMUm+xfGza6wbwnE914yeQ5Ybm18vgM734RZhMgfw4tacUrWseGZlpUrrakEQ==";
      };
    };
    "react-16.8.6" = {
      name = "react";
      packageName = "react";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.8.6.tgz";
        sha512 = "pC0uMkhLaHm11ZSJULfOBqV4tIZkx87ZLvbbQYunNixAAvjnC+snJCg0XQXn9VIsttVsbZP/H/ewzgsd5fxKXw==";
      };
    };
    "react-dom-16.8.6" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.8.6.tgz";
        sha512 = "1nL7PIq9LTL3fthPqwkvr2zY7phIPjYrT0jp4HjyEQrEROnw4dG41VVwi/wfoCneoleqrNX7iAD+pXebJZwrwA==";
      };
    };
    "react-is-16.8.6" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.8.6.tgz";
        sha512 = "aUk3bHfZ2bRSVFFbbeVS4i+lNPZr3/WM5jT2J5omUVV1zzcs1nAaf3l51ctA5FFvCRbhrH0bdAsRRQddFJZPtA==";
      };
    };
    "react-mentions-2.4.2" = {
      name = "react-mentions";
      packageName = "react-mentions";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-mentions/-/react-mentions-2.4.2.tgz";
        sha512 = "il9PuG0lXRoMBjm1JDMEjRaRDmHBFd0O4fOANFZmX/8dIBJhBieO5ii+imNNvVb16/ft4MGxsQq8MgCdLobnTA==";
      };
    };
    "react-photo-gallery-6.3.4" = {
      name = "react-photo-gallery";
      packageName = "react-photo-gallery";
      version = "6.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-photo-gallery/-/react-photo-gallery-6.3.4.tgz";
        sha512 = "G3Trhk/DiGWQHV3ZtP9cNdaIT9ujybp/nNpzHrQLd3nijWaJqqGuGp73y+S3H5zx3DxQKlaOraTX9mdkXC08eA==";
      };
    };
    "react-resize-detector-4.2.0" = {
      name = "react-resize-detector";
      packageName = "react-resize-detector";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-resize-detector/-/react-resize-detector-4.2.0.tgz";
        sha512 = "AtOaNIxs0ydua7tEoglXR3902/EdlIj9PXDu1Zj0ug2VAUnkSQjguLGzaG/N6CXLOhJSccTsUCZxjLayQ1mE9Q==";
      };
    };
    "react-router-4.3.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-4.3.1.tgz";
        sha512 = "yrvL8AogDh2X42Dt9iknk4wF4V8bWREPirFfS9gLU1huk6qK41sg7Z/1S81jjTrGHxa3B8R3J6xIkDAA6CVarg==";
      };
    };
    "react-router-dom-4.3.1" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-4.3.1.tgz";
        sha512 = "c/MlywfxDdCp7EnB7YfPMOfMD3tOtIjrQlj/CKfNMBxdmpJP8xcz5P/UAFn3JbnQCNUxsHyVVqllF9LhgVyFCA==";
      };
    };
    "react-visibility-sensor-5.1.0" = {
      name = "react-visibility-sensor";
      packageName = "react-visibility-sensor";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-visibility-sensor/-/react-visibility-sensor-5.1.0.tgz";
        sha512 = "DnM9+W3sHOPATMG+HLAS2vTqSnC6yizCiUrCFRdgg6whcq8Ed0Vr3hMm11Pkz8wTSgqYnkiKvSWXmviSBI99uQ==";
      };
    };
    "regenerator-runtime-0.13.2" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.2.tgz";
        sha512 = "S/TQAZJO+D3m9xeN1WTI8dLKBBiRgXBlTJvbWjCThHWZj9EvHK70Ff50/tYj2J/fvBY6JtFVwRuazHN2E7M9BA==";
      };
    };
    "resize-observer-polyfill-1.5.1" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.1.tgz";
        sha512 = "LwZrotdHOo12nQuZlHEmtuXdqGoOD0OhaxopaNFxWzInpEgaLWoVuAMbTzixuosCx2nEG58ngzW3vxdWoxIgdg==";
      };
    };
    "resolve-pathname-2.2.0" = {
      name = "resolve-pathname";
      packageName = "resolve-pathname";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pathname/-/resolve-pathname-2.2.0.tgz";
        sha512 = "bAFz9ld18RzJfddgrO2e/0S2O81710++chRMUxHjXOYKF6jTAMrUNZrEZ1PvV0zlhfjidm08iRPdTLPno1FuRg==";
      };
    };
    "scheduler-0.13.6" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.13.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.13.6.tgz";
        sha512 = "IWnObHt413ucAYKsD9J1QShUKkbKLQQHdxRyw73sw4FN26iWr3DY/H34xGPe4nmL1DwXyWmSWmMrA9TfQbE/XQ==";
      };
    };
    "split-on-first-1.1.0" = {
      name = "split-on-first";
      packageName = "split-on-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-on-first/-/split-on-first-1.1.0.tgz";
        sha512 = "43ZssAJaMusuKWL8sKUBQXHWOpq8d6CfN/u1p4gUzfJkM05C8rxTmYrkIPTXapZpORA6LkkzcUulJ8FqA7Uudw==";
      };
    };
    "streamsaver-2.0.3" = {
      name = "streamsaver";
      packageName = "streamsaver";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsaver/-/streamsaver-2.0.3.tgz";
        sha512 = "IpXeZ67YxcsrfZHe3yg/IyZ5KPfRSn1teDy5mRX2e8M6K410NcJNcR+SFQ2Z92DO36VBUArQP4Vy3Qu33MwIOQ==";
      };
    };
    "strict-uri-encode-2.0.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-2.0.0.tgz";
        sha1 = "b9c7330c7042862f6b142dc274bbcc5866ce3546";
      };
    };
    "substyle-6.3.1" = {
      name = "substyle";
      packageName = "substyle";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/substyle/-/substyle-6.3.1.tgz";
        sha512 = "S25YRgVQB25cLXgGAJ7AXTYewkIB/9Fa1Y7jxkN48U4N6rbK9YhVEiF7vtPGLlJl8ebSOJ3N4t8cd6jL8MH7Uw==";
      };
    };
    "tiny-invariant-1.0.5" = {
      name = "tiny-invariant";
      packageName = "tiny-invariant";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-invariant/-/tiny-invariant-1.0.5.tgz";
        sha512 = "BziszNEQNwtyMS9OVJia2LK9N9b6VJ35kBrvhDDDpr4hreLYqhCie15dB35uZMdqv9ZTQ55GHQtkz2FnleTHIA==";
      };
    };
    "tiny-warning-1.0.3" = {
      name = "tiny-warning";
      packageName = "tiny-warning";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-warning/-/tiny-warning-1.0.3.tgz";
        sha512 = "lBN9zLN/oAf68o3zNXYrdCt1kP8WsiGW8Oo2ka41b2IM5JL/S1CTyX1rW0mb/zSuJun0ZUrDxx4sqvYS2FWzPA==";
      };
    };
    "uikit-3.1.6" = {
      name = "uikit";
      packageName = "uikit";
      version = "3.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uikit/-/uikit-3.1.6.tgz";
        sha512 = "S4+1kPUbBXcAc8kO8OhZRgawcp6gmMK9BSx865vsun4ul/rXwgQ95i/3hF2axchQ5Gb6ncH1VfUpfKiOfFecsA==";
      };
    };
    "underscore-1.9.1" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz";
        sha512 = "5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==";
      };
    };
    "url-toolkit-2.1.6" = {
      name = "url-toolkit";
      packageName = "url-toolkit";
      version = "2.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-toolkit/-/url-toolkit-2.1.6.tgz";
        sha512 = "UaZ2+50am4HwrV2crR/JAf63Q4VvPYphe63WGeoJxeu8gmOm0qxPt+KsukfakPNrX9aymGNEkkaoICwn+OuvBw==";
      };
    };
    "utf8-3.0.0" = {
      name = "utf8";
      packageName = "utf8";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8/-/utf8-3.0.0.tgz";
        sha512 = "E8VjFIQ/TyQgp+TZfS6l8yp/xWppSAHzidGiRrqe4bK4XP9pTRyKFgGJpO3SN7zdX4DeomTrwaseCHovfpFcqQ==";
      };
    };
    "value-equal-0.4.0" = {
      name = "value-equal";
      packageName = "value-equal";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-equal/-/value-equal-0.4.0.tgz";
        sha512 = "x+cYdNnaA3CxvMaTX0INdTCN8m8aF2uY9BvEqmxuYp8bL09cs/kWVQPVGcA35fMktdOsP69IgU7wFj/61dJHEw==";
      };
    };
    "vcard-parser-1.0.0" = {
      name = "vcard-parser";
      packageName = "vcard-parser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vcard-parser/-/vcard-parser-1.0.0.tgz";
        sha512 = "rSEjrjBK3of4VimMR5vBjLLcN5ZCSp9yuVzyx5i4Fwx74Yd0s+DnHtSit/wAAtj1a7/T/qQc0ykwXADoD0+fTQ==";
      };
    };
    "warning-2.1.0" = {
      name = "warning";
      packageName = "warning";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-2.1.0.tgz";
        sha1 = "21220d9c63afc77a8c92111e011af705ce0c6901";
      };
    };
    "warning-4.0.3" = {
      name = "warning";
      packageName = "warning";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-4.0.3.tgz";
        sha512 = "rpJyN222KWIvHJ/F53XSZv0Zl/accqHR8et1kpaMTD/fLCRxtV8iX8czMzY7sVZupTI3zcUTg8eycS2kNF9l6w==";
      };
    };
    "web-streams-polyfill-1.3.2" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-1.3.2.tgz";
        sha1 = "3719245e909282d93967825f44bcd550e9c03995";
      };
    };
    "webpack-merge-4.2.1" = {
      name = "webpack-merge";
      packageName = "webpack-merge";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-merge/-/webpack-merge-4.2.1.tgz";
        sha512 = "4p8WQyS98bUJcCvFMbdGZyZmsKuWjWVnVHnAS3FFg0HDaRVrPbkivx2RYCre8UiemD67RsiFFLfn4JhLAin8Vw==";
      };
    };
  };
  args = {
    name = "intrustd-photo-app";
    packageName = "intrustd-photo-app";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.5.4"
      sources."base64-js-1.3.0"
      sources."bootstrap-4.3.1"
      sources."buffer-5.2.1"
      sources."cache-polyfill-1.0.1"
      sources."decode-uri-component-0.2.0"
      sources."dexie-2.0.4"
      sources."event-target-shim-3.0.2"
      sources."eventemitter3-3.1.0"
      sources."font-awesome-4.7.0"
      sources."history-4.9.0"
      sources."hls.js-0.12.4"
      sources."hoist-non-react-statics-3.3.0"
      sources."http-parser-js-0.4.13"
      sources."ieee754-1.1.13"
      sources."immutable-3.8.2"
      sources."intrustd-git://github.com/intrustd/js"
      sources."invariant-2.2.4"
      sources."isarray-0.0.1"
      sources."jquery-3.4.1"
      sources."js-tokens-4.0.0"
      sources."lodash-4.17.14"
      sources."lodash-es-4.17.14"
      sources."loose-envify-1.4.0"
      sources."mithril-1.1.6"
      sources."nprogress-0.2.0"
      sources."object-assign-4.1.1"
      sources."path-to-regexp-1.7.0"
      sources."popper.js-1.15.0"
      sources."prop-types-15.7.2"
      sources."query-string-6.8.1"
      sources."raf-schd-4.0.2"
      sources."react-16.8.6"
      sources."react-dom-16.8.6"
      sources."react-is-16.8.6"
      sources."react-mentions-2.4.2"
      sources."react-photo-gallery-6.3.4"
      sources."react-resize-detector-4.2.0"
      (sources."react-router-4.3.1" // {
        dependencies = [
          sources."hoist-non-react-statics-2.5.5"
          sources."warning-4.0.3"
        ];
      })
      (sources."react-router-dom-4.3.1" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      sources."react-visibility-sensor-5.1.0"
      sources."regenerator-runtime-0.13.2"
      sources."resize-observer-polyfill-1.5.1"
      sources."resolve-pathname-2.2.0"
      sources."scheduler-0.13.6"
      sources."split-on-first-1.1.0"
      sources."streamsaver-2.0.3"
      sources."strict-uri-encode-2.0.0"
      sources."substyle-6.3.1"
      sources."tiny-invariant-1.0.5"
      sources."tiny-warning-1.0.3"
      sources."uikit-3.1.6"
      sources."underscore-1.9.1"
      sources."url-toolkit-2.1.6"
      sources."utf8-3.0.0"
      sources."value-equal-0.4.0"
      sources."vcard-parser-1.0.0"
      sources."warning-2.1.0"
      sources."web-streams-polyfill-1.3.2"
      sources."webpack-merge-4.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The default Photos application that ships with intrustd";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}