# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/code-frame-7.8.3" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.8.3.tgz";
        sha512 = "a9gxpmdXtZEInkCSHUJDLHZVBgb1QS0jhss4cPP93EW7s+uC5bikET2twEF3KV+7rDblJcmNvTR7VJejqd2C2g==";
      };
    };
    "@babel/helper-module-imports-7.8.3" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.8.3.tgz";
        sha512 = "R0Bx3jippsbAEtzkpZ/6FIiuzOURPcMjHp+Z6xPe6DtApDJx+w7UYyOLanZqO8+wKR9G10s/FmHXvxaMd9s6Kg==";
      };
    };
    "@babel/helper-validator-identifier-7.9.0" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.9.0.tgz";
        sha512 = "6G8bQKjOh+of4PV/ThDm/rRqlU7+IGoJuofpagU5GlEl29Vv0RGqqt86ZGRV8ZuSOY3o+8yXl5y782SMcG7SHw==";
      };
    };
    "@babel/highlight-7.9.0" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.9.0.tgz";
        sha512 = "lJZPilxX7Op3Nv/2cvFdnlepPXDxi29wxteT57Q965oc5R9v86ztx0jfxVrTcBk8C2kcPkkDa2Z4T3ZsPPVWsQ==";
      };
    };
    "@babel/runtime-7.9.2" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.9.2.tgz";
        sha512 = "NE2DtOdufG7R5vnfQUTehdTfNycfUANEtCa9PssN9O/xmTzP4E08UI797ixaei6hBEVL9BI/PsdJS5x7mWoB9Q==";
      };
    };
    "@babel/types-7.9.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.9.0.tgz";
        sha512 = "BS9JKfXkzzJl8RluW4JGknzpiUV7ZrvTayM6yfqLTVBEnFtyowVIOu6rqxRd5cVO6yGoWf4T8u8dgK9oB+GCng==";
      };
    };
    "@emotion/cache-10.0.29" = {
      name = "_at_emotion_slash_cache";
      packageName = "@emotion/cache";
      version = "10.0.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/cache/-/cache-10.0.29.tgz";
        sha512 = "fU2VtSVlHiF27empSbxi1O2JFdNWZO+2NFHfwO0pxgTep6Xa3uGb+3pVKfLww2l/IBGLNEZl5Xf/++A4wAYDYQ==";
      };
    };
    "@emotion/core-10.0.28" = {
      name = "_at_emotion_slash_core";
      packageName = "@emotion/core";
      version = "10.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/core/-/core-10.0.28.tgz";
        sha512 = "pH8UueKYO5jgg0Iq+AmCLxBsvuGtvlmiDCOuv8fGNYn3cowFpLN98L8zO56U0H1PjDIyAlXymgL3Wu7u7v6hbA==";
      };
    };
    "@emotion/css-10.0.27" = {
      name = "_at_emotion_slash_css";
      packageName = "@emotion/css";
      version = "10.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/css/-/css-10.0.27.tgz";
        sha512 = "6wZjsvYeBhyZQYNrGoR5yPMYbMBNEnanDrqmsqS1mzDm1cOTu12shvl2j4QHNS36UaTE0USIJawCH9C8oW34Zw==";
      };
    };
    "@emotion/hash-0.8.0" = {
      name = "_at_emotion_slash_hash";
      packageName = "@emotion/hash";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/hash/-/hash-0.8.0.tgz";
        sha512 = "kBJtf7PH6aWwZ6fka3zQ0p6SBYzx4fl1LoZXE2RrnYST9Xljm7WfKJrU4g/Xr3Beg72MLrp1AWNUmuYJTL7Cow==";
      };
    };
    "@emotion/memoize-0.7.4" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz";
        sha512 = "Ja/Vfqe3HpuzRsG1oBtWTHk2PGZ7GR+2Vz5iYGelAw8dx32K0y7PjVuxK6z1nMpZOqAFsRUPCkK1YjJ56qJlgw==";
      };
    };
    "@emotion/serialize-0.11.16" = {
      name = "_at_emotion_slash_serialize";
      packageName = "@emotion/serialize";
      version = "0.11.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/serialize/-/serialize-0.11.16.tgz";
        sha512 = "G3J4o8by0VRrO+PFeSc3js2myYNOXVJ3Ya+RGVxnshRYgsvErfAOglKAiy1Eo1vhzxqtUvjCyS5gtewzkmvSSg==";
      };
    };
    "@emotion/sheet-0.9.4" = {
      name = "_at_emotion_slash_sheet";
      packageName = "@emotion/sheet";
      version = "0.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/sheet/-/sheet-0.9.4.tgz";
        sha512 = "zM9PFmgVSqBw4zL101Q0HrBVTGmpAxFZH/pYx/cjJT5advXguvcgjHFTCaIO3enL/xr89vK2bh0Mfyj9aa0ANA==";
      };
    };
    "@emotion/stylis-0.8.5" = {
      name = "_at_emotion_slash_stylis";
      packageName = "@emotion/stylis";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/stylis/-/stylis-0.8.5.tgz";
        sha512 = "h6KtPihKFn3T9fuIrwvXXUOwlx3rfUvfZIcP5a6rh8Y7zjE3O06hT5Ss4S/YI1AYhuZ1kjaE/5EaOOI2NqSylQ==";
      };
    };
    "@emotion/unitless-0.7.5" = {
      name = "_at_emotion_slash_unitless";
      packageName = "@emotion/unitless";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/unitless/-/unitless-0.7.5.tgz";
        sha512 = "OWORNpfjMsSSUBVrRBVGECkhWcULOAJz9ZW8uK9qgxD+87M7jHRcvh/A96XXNhXTLmKcoYSQtBEX7lHMO7YRwg==";
      };
    };
    "@emotion/utils-0.11.3" = {
      name = "_at_emotion_slash_utils";
      packageName = "@emotion/utils";
      version = "0.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/utils/-/utils-0.11.3.tgz";
        sha512 = "0o4l6pZC+hI88+bzuaX/6BgOvQVhbt2PfmxauVaYOGgbsAw14wdKyvMCZXnsnsHys94iadcF+RG/wZyx6+ZZBw==";
      };
    };
    "@emotion/weak-memoize-0.2.5" = {
      name = "_at_emotion_slash_weak-memoize";
      packageName = "@emotion/weak-memoize";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/weak-memoize/-/weak-memoize-0.2.5.tgz";
        sha512 = "6U71C2Wp7r5XtFtQzYrW5iKFT67OixrSxjI4MptCHzdSVlgabczzqLe0ZSgnub/5Kp4hSbpDB1tMytZY9pwxxA==";
      };
    };
    "@fortawesome/fontawesome-free-5.13.0" = {
      name = "_at_fortawesome_slash_fontawesome-free";
      packageName = "@fortawesome/fontawesome-free";
      version = "5.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.13.0.tgz";
        sha512 = "xKOeQEl5O47GPZYIMToj6uuA2syyFlq9EMSl2ui0uytjY9xbe8XS0pexNWmxrdcCyNGyDmLyYw5FtKsalBUeOg==";
      };
    };
    "@popperjs/core-2.1.1" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.1.1.tgz";
        sha512 = "sLqWxCzC5/QHLhziXSCAksBxHfOnQlhPRVgPK0egEw+ktWvG75T2k+aYWVjVh9+WKeT3tlG3ZNbZQvZLmfuOIw==";
      };
    };
    "@restart/context-2.1.4" = {
      name = "_at_restart_slash_context";
      packageName = "@restart/context";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@restart/context/-/context-2.1.4.tgz";
        sha512 = "INJYZQJP7g+IoDUh/475NlGiTeMfwTXUEr3tmRneckHIxNolGOW9CTq83S8cxq0CgJwwcMzMJFchxvlwe7Rk8Q==";
      };
    };
    "@restart/hooks-0.3.22" = {
      name = "_at_restart_slash_hooks";
      packageName = "@restart/hooks";
      version = "0.3.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@restart/hooks/-/hooks-0.3.22.tgz";
        sha512 = "tW0T3hP6emYNOc76/iC96rlu+f7JYLSVk/Wnn+7dj1gJUcw4CkQNLy16vx2mBLtVKsFMZ9miVEZXat8blruDHQ==";
      };
    };
    "@types/parse-json-4.0.0" = {
      name = "_at_types_slash_parse-json";
      packageName = "@types/parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse-json/-/parse-json-4.0.0.tgz";
        sha512 = "//oorEZjL6sbPcKUaCdIGlIUeH26mgzimjBB77G6XRgnDl/L5wOnpyBGRe/Mmf5CVW3PwEBE1NjiMZ/ssFh4wA==";
      };
    };
    "@types/prop-types-15.7.3" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.3.tgz";
        sha512 = "KfRL3PuHmqQLOG+2tGpRO26Ctg+Cq1E01D2DMriKEATHgWLfeNDmq9e29Q9WIky0dQ3NPkd1mzYH8Lm936Z9qw==";
      };
    };
    "@types/react-16.9.27" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "16.9.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-16.9.27.tgz";
        sha512 = "j+RvQb9w7a2kZFBOgTh+s/elCwtqWUMN6RJNdmz0ntmwpeoMHKnyhUcmYBu7Yw94Rtj9938D+TJSn6WGcq2+OA==";
      };
    };
    "@wojtekmaj/date-utils-1.0.2" = {
      name = "_at_wojtekmaj_slash_date-utils";
      packageName = "@wojtekmaj/date-utils";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wojtekmaj/date-utils/-/date-utils-1.0.2.tgz";
        sha512 = "sOu+uH3jzsECLg3YGH++/pLWs8S4eKiXMwMIcotE62CO9AB/HRyhZ0ISwann/30DLnfCw4skvr8h9gF3aafhPA==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "array-move-2.2.1" = {
      name = "array-move";
      packageName = "array-move";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-move/-/array-move-2.2.1.tgz";
        sha512 = "qQpEHBnVT6HAFgEVUwRdHVd8TYJThrZIT5wSXpEUTPwBaYhPLclw12mEpyUvRWVdl1VwPOqnIy6LqTFN3cSeUQ==";
      };
    };
    "babel-plugin-emotion-10.0.29" = {
      name = "babel-plugin-emotion";
      packageName = "babel-plugin-emotion";
      version = "10.0.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-emotion/-/babel-plugin-emotion-10.0.29.tgz";
        sha512 = "7Jpi1OCxjyz0k163lKtqP+LHMg5z3S6A7vMBfHnF06l2unmtsOmFDzZBpGf0CWo1G4m8UACfVcDJiSiRuu/cSw==";
      };
    };
    "babel-plugin-macros-2.8.0" = {
      name = "babel-plugin-macros";
      packageName = "babel-plugin-macros";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-macros/-/babel-plugin-macros-2.8.0.tgz";
        sha512 = "SEP5kJpfGYqYKpBrj5XU3ahw5p5GOHJ0U5ssOSQ/WBVdwkD2Dzlce95exQTs3jOVWPPKLBN2rlEWkCK7dSmLvg==";
      };
    };
    "babel-plugin-syntax-jsx-6.18.0" = {
      name = "babel-plugin-syntax-jsx";
      packageName = "babel-plugin-syntax-jsx";
      version = "6.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-plugin-syntax-jsx/-/babel-plugin-syntax-jsx-6.18.0.tgz";
        sha1 = "0af32a9a6e13ca7a3fd5069e62d7b0f58d0d8946";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "blacklist-1.1.4" = {
      name = "blacklist";
      packageName = "blacklist";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blacklist/-/blacklist-1.1.4.tgz";
        sha1 = "b2dd09d6177625b2caa69835a37b28995fa9a2f2";
      };
    };
    "bootstrap-4.4.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-4.4.1.tgz";
        sha512 = "tbx5cHubwE6e2ZG7nqM3g/FZ5PQEDMWmMGNrCUBVRPHXTJaH7CBDdsLeu3eCh3B1tzAxTnAbtmrzvWEvT2NNEA==";
      };
    };
    "buffer-5.5.0" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.5.0.tgz";
        sha512 = "9FTEDjLjwoAkEwyMGDjYJQN2gfRgOKBKRfiglhvibGbpeeU/pQn1bJxQqm32OD/AIeEuHxU9roxXxg34Byp/Ww==";
      };
    };
    "cache-polyfill-1.0.1" = {
      name = "cache-polyfill";
      packageName = "cache-polyfill";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-polyfill/-/cache-polyfill-1.0.1.tgz";
        sha512 = "bIMkvMYuXvOOUMoxUChREYXT6OZi4kvPcRQrmEyaPkLR21sLwDfhdhxxSifZmoiPGQHNEdbeuVNtO5oXbSP31Q==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "chain-function-1.0.1" = {
      name = "chain-function";
      packageName = "chain-function";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chain-function/-/chain-function-1.0.1.tgz";
        sha512 = "SxltgMwL9uCko5/ZCLiyG2B7R9fY4pDZUw7hJ4MhirdjBLosoDqkWABi3XMucddHdLiFJMb7PD2MZifZriuMTg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chrono-node-1.4.4" = {
      name = "chrono-node";
      packageName = "chrono-node";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrono-node/-/chrono-node-1.4.4.tgz";
        sha512 = "vwsQ2Z6RhkfIsFYvcZtifa0eSQC6pl08fgXkcZXkfGAJk/OkdYAuGqM2yLhPzsuK3N+BmaKFBie/jGvLsiYMbA==";
      };
    };
    "classnames-2.2.6" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.6.tgz";
        sha512 = "JR/iSQOSt+LQIWwrwEzJ9uk0xfN3mTVYMwt1Ir5mUcSN6pU+V4zQFFaJsclJbPuAUQH+yfWef6tm7l1quW3C8Q==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "convert-source-map-1.7.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.7.0.tgz";
        sha512 = "4FJkXzKXEDB1snCFZlLP4gpC3JILicCpGbzG9f9G7tGqGCzETQ2hWPrcinA9oU4wtf2biUaEH5065UnMeR33oA==";
      };
    };
    "cosmiconfig-6.0.0" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-6.0.0.tgz";
        sha512 = "xb3ZL6+L8b9JLLCx3ZdoZy4+2ECphCMo2PwqgP1tlfVq6M6YReyzBJtvWWtbDSpNr9hn96pkCiZqUcFEc+54Qg==";
      };
    };
    "csstype-2.6.9" = {
      name = "csstype";
      packageName = "csstype";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-2.6.9.tgz";
        sha512 = "xz39Sb4+OaTsULgUERcCk+TJj8ylkL4aSVDQiX/ksxbELSqwkgt4d4RD7fovIdgJGSuNYqwZEiVjYY5l0ask+Q==";
      };
    };
    "dayjs-1.8.23" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.8.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.8.23.tgz";
        sha512 = "NmYHMFONftoZbeOhVz6jfiXI4zSiPN6NoVWJgC0aZQfYVwzy/ZpESPHuCcI0B8BUMpSJQ08zenHDbofOLKq8hQ==";
      };
    };
    "decode-uri-component-0.2.0" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz";
        sha1 = "eb3913333458775cb84cd1a1fae062106bb87545";
      };
    };
    "dexie-2.0.4" = {
      name = "dexie";
      packageName = "dexie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dexie/-/dexie-2.0.4.tgz";
        sha512 = "aQ/s1U2wHxwBKRrt2Z/mwFNHMQWhESerFsMYzE+5P5OsIe5o1kgpFMWkzKTtkvkyyEni6mWr/T4HUJuY9xIHLA==";
      };
    };
    "dom-helpers-3.4.0" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-3.4.0.tgz";
        sha512 = "LnuPJ+dwqKDIyotW1VzmOZ5TONUN7CwkCR5hrgawTUbkBGYdeoNLZo6nNfGkCrjtE1nXXaj7iMMpDa8/d9WoIA==";
      };
    };
    "dom-helpers-5.1.3" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-5.1.3.tgz";
        sha512 = "nZD1OtwfWGRBWlpANxacBEZrEuLa16o1nh7YopFWeoF68Zt8GGEmzHu6Xv4F3XaFIC+YXtTLrzgqKxFgLEe4jw==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domhandler-3.0.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-3.0.0.tgz";
        sha512 = "eKLdI5v9m67kbXQbJSNn1zjh0SDzvzWVWtX+qEI3eMjZw8daH9k8rlj1FZY9memPwjiskQFbe7vHVVJIAqoEhw==";
      };
    };
    "domutils-2.0.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.0.0.tgz";
        sha512 = "n5SelJ1axbO636c2yUtOGia/IcJtVtlhQbFiVDBZHKV5ReJO1ViX7sFEemtuyoAnBxk5meNSYgA8V4s0271efg==";
      };
    };
    "entities-2.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.0.tgz";
        sha512 = "D9f7V0JSRwIxlRI2mjMqufDrRDnx8p+eEOz7aUM9SuvF8gsBzra0/6tbjl1m8eQHrZlYj6PxqE00hZ1SAIKPLw==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "event-target-shim-3.0.2" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-3.0.2.tgz";
        sha512 = "HK5GhnEAkm7fLy249GtF7DIuYmjLm85Ft6ssj7DhVl8Tx/z9+v0W6aiIVUdT4AXWGYy5Fc+s6gqBI49Bf0LejQ==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "eventemitter3-3.1.0" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.0.tgz";
        sha512 = "ivIvhpq/Y0uSjcHDcOIccjmYjGLcP09MFGE7ysAwkAvkXfpZlC985pH2/ui64DKazbTW/4kN3yqozUxlXzI6cA==";
      };
    };
    "find-root-1.1.0" = {
      name = "find-root";
      packageName = "find-root";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-root/-/find-root-1.1.0.tgz";
        sha512 = "NKfW6bec6GfKc0SGx1e07QZY9PE99u0Bft/0rzSD5k3sO/vwkVUpDUKVm5Gpp5Ue3YfShPFTX2070tDs5kB9Ng==";
      };
    };
    "fingertree-js-1.0.2" = {
      name = "fingertree-js";
      packageName = "fingertree-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fingertree-js/-/fingertree-js-1.0.2.tgz";
        sha512 = "O3X24Xcm8RcA4VURHW3G//J9LZeG08o+RSD56ANcUZ+JC9cKvlWssPEB9hIPTxEjPpaf/ci+onPN6hNLLsjfmA==";
      };
    };
    "get-user-locale-1.3.0" = {
      name = "get-user-locale";
      packageName = "get-user-locale";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-user-locale/-/get-user-locale-1.3.0.tgz";
        sha512 = "c5N8P0upjxCF9unIC2vTA+B+8nN7kU/D/TeItMAVYhWIIksyoULM1aflKflXM3w+Ij6vF/JZys+QcwIoDuy3Ag==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "history-4.10.1" = {
      name = "history";
      packageName = "history";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-4.10.1.tgz";
        sha512 = "36nwAD620w12kuzPAsyINPWJqlNbij+hpK1k9XRloDtym8mxzGYl2c17LnV6IAGB2Dmg4tEa7G7DlawS0+qjew==";
      };
    };
    "hls.js-0.12.4" = {
      name = "hls.js";
      packageName = "hls.js";
      version = "0.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hls.js/-/hls.js-0.12.4.tgz";
        sha512 = "e8OPxQ60dBVsdkv4atdxR21KzC1mgwspM41qpozpj3Uv1Fz4CaeQy3FWoaV2O+QKKbNRvV5hW+/LipCWdrwnMQ==";
      };
    };
    "hoist-non-react-statics-2.5.5" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "2.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-2.5.5.tgz";
        sha512 = "rqcy4pJo55FTTLWt+bU8ukscqHeE/e9KWvsOW2b/a3afxQZhwkQdT1rPPCJ0rYXdj4vNcasY8zHTH+jF/qStxw==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "htmlparser2-4.1.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-4.1.0.tgz";
        sha512 = "4zDq1a1zhE4gQso/c5LP1OtrhYTncXNSpvJYtWJBtXAETPlMfi3IFNjGuQbYLuVY4ZR0QMqRVvo4Pdy9KLyP8Q==";
      };
    };
    "http-parser-js-0.4.13" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.13.tgz";
        sha1 = "3bd6d6fde6e3172c9334c3b33b6c193d80fe1137";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "immutable-3.8.2" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.8.2.tgz";
        sha1 = "c2439951455bb39913daf281376f1530e104adf3";
      };
    };
    "import-fresh-3.2.1" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.2.1.tgz";
        sha512 = "6e1q1cnWP2RXD9/keSkxHScg508CdXqXWgWBaETNhyuBFz+kUZlKboh+ISK+bU++DmbHimVBrOz/zzPe0sZ3sQ==";
      };
    };
    "intrustd-../../../js" = {
      name = "intrustd";
      packageName = "intrustd";
      version = "1.0.0";
      src = ../../../js;
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "jquery-3.4.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz";
        sha512 = "36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-parse-better-errors-1.0.2" = {
      name = "json-parse-better-errors";
      packageName = "json-parse-better-errors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz";
        sha512 = "mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==";
      };
    };
    "lines-and-columns-1.1.6" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz";
        sha1 = "1c00c743b433cd0a4e80758f7b64a57440d9ff00";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lodash-es-4.17.15" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.15.tgz";
        sha512 = "rlrc3yU3+JNOpZ9zj5pQtxnx2THmvRykwL4Xlxoa8I9lHBlVbbyPhgyPMioxVZ4NqyxaVVtaJnzsyOidQIhyyQ==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.escaperegexp-4.1.2" = {
      name = "lodash.escaperegexp";
      packageName = "lodash.escaperegexp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.escaperegexp/-/lodash.escaperegexp-4.1.2.tgz";
        sha1 = "64762c48618082518ac3df4ccf5d5886dae20347";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.mergewith-4.6.2" = {
      name = "lodash.mergewith";
      packageName = "lodash.mergewith";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.mergewith/-/lodash.mergewith-4.6.2.tgz";
        sha512 = "GK3g5RPZWTRSeLSpgP8Xhra+pnjBC56q9FZYe1d5RN3TJ35dbkGy3YqBSMbyCrlbi+CM9Z3Jk5yTL7RCsqboyQ==";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha1 = "0dd3971213c7c56df880977d504c88fb471a97ac";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "medium-editor-5.23.3" = {
      name = "medium-editor";
      packageName = "medium-editor";
      version = "5.23.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/medium-editor/-/medium-editor-5.23.3.tgz";
        sha512 = "he9/TdjX8f8MGdXGfCs8AllrYnqXJJvjNkDKmPg3aPW/uoIrlRqtkFthrwvmd+u4QyzEiadhCCM0EwTiRdUCJw==";
      };
    };
    "memoize-one-5.1.1" = {
      name = "memoize-one";
      packageName = "memoize-one";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memoize-one/-/memoize-one-5.1.1.tgz";
        sha512 = "HKeeBpWvqiVJD57ZUAsJNm71eHTykffzcLZVYWiVfQeI1rJtuEaS7hQiEpWfVVk18donPwJEcFKIkCmPJNOhHA==";
      };
    };
    "merge-class-names-1.3.0" = {
      name = "merge-class-names";
      packageName = "merge-class-names";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-class-names/-/merge-class-names-1.3.0.tgz";
        sha512 = "k0Qaj36VBpKgdc8c188LEZvo6v/zzry/FUufwopWbMSp6/knfVFU/KIB55/hJjeIpg18IH2WskXJCRnM/1BrdQ==";
      };
    };
    "mithril-1.1.7" = {
      name = "mithril";
      packageName = "mithril";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mithril/-/mithril-1.1.7.tgz";
        sha512 = "1SAkGeVrIVvkUHlPHvR3pXdWzNfTzmS/fBAe+rC2ApEBfZFFc+idi8Qg/M5JoW/sZkIDXSfQYVgvENMIhBIVAg==";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "nprogress-0.2.0" = {
      name = "nprogress";
      packageName = "nprogress";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nprogress/-/nprogress-0.2.0.tgz";
        sha1 = "cb8f34c53213d895723fcbab907e9422adbcafb1";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "parse-json-5.0.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-5.0.0.tgz";
        sha512 = "OOY5b7PAEFV0E2Fir1KOkxchnZNCdowAJgQ5NuxjpBKTRP3pQhwkrkxqQjeoKJ+fO7bCpmIZaogI4eZGDMEGOw==";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-to-regexp-1.8.0" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-1.8.0.tgz";
        sha512 = "n43JRhlUKUAlibEJhPeir1ncUID16QnEjNpwzNdO3Lm4ywrBpBZ5oLD0I6br9evr1Y9JTqwRtAh7JLoOzAQdVA==";
      };
    };
    "path-type-4.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
        sha512 = "gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
      };
    };
    "popper.js-1.16.1" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.16.1.tgz";
        sha512 = "Wb4p1J4zyFTbM+u6WuO4XstYx4Ky9Cewe4DWrel7B0w6VVICvPwdOpotjzcf6eD8TsckVnIMNONQyPIUFOUbCQ==";
      };
    };
    "postcss-7.0.27" = {
      name = "postcss";
      packageName = "postcss";
      version = "7.0.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-7.0.27.tgz";
        sha512 = "WuQETPMcW9Uf1/22HWUWP9lgsIC+KEHg2kozMflKjbeUtw9ujvFX6QmIfozaErDkmLWS9WEnEdEe6Uo9/BNTdQ==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "prop-types-extra-1.1.1" = {
      name = "prop-types-extra";
      packageName = "prop-types-extra";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types-extra/-/prop-types-extra-1.1.1.tgz";
        sha512 = "59+AHNnHYCdiC+vMwY52WmvP5dM3QLeoumYuEyceQDi9aEhtwN9zIQ2ZNo25sMyXnbh32h+P1ezDsUpUH3JAew==";
      };
    };
    "query-string-6.11.1" = {
      name = "query-string";
      packageName = "query-string";
      version = "6.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-6.11.1.tgz";
        sha512 = "1ZvJOUl8ifkkBxu2ByVM/8GijMIPx+cef7u3yroO3Ogm4DOdZcF5dcrWTIlSHe3Pg/mtlt6/eFjObDfJureZZA==";
      };
    };
    "querystringify-2.1.1" = {
      name = "querystringify";
      packageName = "querystringify";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystringify/-/querystringify-2.1.1.tgz";
        sha512 = "w7fLxIRCRT7U8Qu53jQnJyPkYZIaR4n5151KMfcJlO/A9397Wxb1amJvROTK6TOnp7PfoAmg/qXiNHI+08jRfA==";
      };
    };
    "raf-schd-4.0.2" = {
      name = "raf-schd";
      packageName = "raf-schd";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raf-schd/-/raf-schd-4.0.2.tgz";
        sha512 = "VhlMZmGy6A6hrkJWHLNTGl5gtgMUm+xfGza6wbwnE914yeQ5Ybm18vgM734RZhMgfw4tacUrWseGZlpUrrakEQ==";
      };
    };
    "react-16.13.1" = {
      name = "react";
      packageName = "react";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.13.1.tgz";
        sha512 = "YMZQQq32xHLX0bz5Mnibv1/LHb3Sqzngu7xstSM+vrkE5Kzr9xE0yMByK5kMoTK30YVJE61WfbxIFFvfeDKT1w==";
      };
    };
    "react-addons-css-transition-group-15.6.2" = {
      name = "react-addons-css-transition-group";
      packageName = "react-addons-css-transition-group";
      version = "15.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-addons-css-transition-group/-/react-addons-css-transition-group-15.6.2.tgz";
        sha1 = "9e4376bcf40b5217d14ec68553081cee4b08a6d6";
      };
    };
    "react-bootstrap-1.0.0" = {
      name = "react-bootstrap";
      packageName = "react-bootstrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-bootstrap/-/react-bootstrap-1.0.0.tgz";
        sha512 = "Ep6ZNH6wL5m9bytOS6T9mjSz0YE1bEkc+uHItvenRcA3amr5ApkpKYzAWgdglhRPZHPvm+pnqs1z5IPwv/2UZw==";
      };
    };
    "react-calendar-3.0.1" = {
      name = "react-calendar";
      packageName = "react-calendar";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-calendar/-/react-calendar-3.0.1.tgz";
        sha512 = "EGzmSZXYVxMhhGWFZKEW6I5RFWwi7TrhJIwPIFTTW2nGuMed4aHS51degFEvvSQNf6jt/LLwcXxbwC2U6D2BIg==";
      };
    };
    "react-dom-16.13.1" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz";
        sha512 = "81PIMmVLnCNLO/fFOQxdQkvEq/+Hfpv24XNJfpyZhTRfO0QcmQIF/PgCa1zCOj2w1hrn12MFLyaJ/G0+Mxtfag==";
      };
    };
    "react-draggable-4.2.0" = {
      name = "react-draggable";
      packageName = "react-draggable";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-draggable/-/react-draggable-4.2.0.tgz";
        sha512 = "5wFq//gEoeTYprnd4ze8GrFc+Rbnx+9RkOMR3vk4EbWxj02U6L6T3yrlKeiw4X5CtjD2ma2+b3WujghcXNRzkw==";
      };
    };
    "react-input-autosize-2.2.2" = {
      name = "react-input-autosize";
      packageName = "react-input-autosize";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-input-autosize/-/react-input-autosize-2.2.2.tgz";
        sha512 = "jQJgYCA3S0j+cuOwzuCd1OjmBmnZLdqQdiLKRYrsMMzbjUrVDS5RvJUDwJqA7sKuksDuzFtm6hZGKFu7Mjk5aw==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-lifecycles-compat-3.0.4" = {
      name = "react-lifecycles-compat";
      packageName = "react-lifecycles-compat";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-lifecycles-compat/-/react-lifecycles-compat-3.0.4.tgz";
        sha512 = "fBASbA6LnOU9dOU2eW7aQ8xmYBSXUIWr+UmF9b1efZBazGNO+rcXT/icdKnYm2pTwcRylVUYwW7H1PHfLekVzA==";
      };
    };
    "react-medium-editor-1.8.1" = {
      name = "react-medium-editor";
      packageName = "react-medium-editor";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-medium-editor/-/react-medium-editor-1.8.1.tgz";
        sha1 = "016ffc3bb82f9364af15f7e43be75d6882555f5a";
      };
    };
    "react-mentions-2.4.2" = {
      name = "react-mentions";
      packageName = "react-mentions";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-mentions/-/react-mentions-2.4.2.tgz";
        sha512 = "il9PuG0lXRoMBjm1JDMEjRaRDmHBFd0O4fOANFZmX/8dIBJhBieO5ii+imNNvVb16/ft4MGxsQq8MgCdLobnTA==";
      };
    };
    "react-moment-0.9.7" = {
      name = "react-moment";
      packageName = "react-moment";
      version = "0.9.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-moment/-/react-moment-0.9.7.tgz";
        sha512 = "ifzUrUGF6KRsUN2pRG5k56kO0mJBr8kRkWb0wNvtFIsBIxOuPxhUpL1YlXwpbQCbHq23hUu6A0VEk64HsFxk9g==";
      };
    };
    "react-overlays-3.0.1" = {
      name = "react-overlays";
      packageName = "react-overlays";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-overlays/-/react-overlays-3.0.1.tgz";
        sha512 = "QEt6I3Cjy06pe2FwY/tuWaXEzSVOuXfP8zsC6oWHJhMYpEJQgZV/TCwbCw5slMW6VcgwcWPc4HrBzN0yfxf5Xw==";
      };
    };
    "react-resize-detector-4.2.1" = {
      name = "react-resize-detector";
      packageName = "react-resize-detector";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-resize-detector/-/react-resize-detector-4.2.1.tgz";
        sha512 = "ZfPMBPxXi0o3xox42MIEtz84tPSVMW9GgwLHYvjVXlFM+OkNzbeEtpVSV+mSTJmk4Znwomolzt35zHN9LNBQMQ==";
      };
    };
    "react-router-4.3.1" = {
      name = "react-router";
      packageName = "react-router";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-4.3.1.tgz";
        sha512 = "yrvL8AogDh2X42Dt9iknk4wF4V8bWREPirFfS9gLU1huk6qK41sg7Z/1S81jjTrGHxa3B8R3J6xIkDAA6CVarg==";
      };
    };
    "react-router-dom-4.3.1" = {
      name = "react-router-dom";
      packageName = "react-router-dom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router-dom/-/react-router-dom-4.3.1.tgz";
        sha512 = "c/MlywfxDdCp7EnB7YfPMOfMD3tOtIjrQlj/CKfNMBxdmpJP8xcz5P/UAFn3JbnQCNUxsHyVVqllF9LhgVyFCA==";
      };
    };
    "react-select-3.1.0" = {
      name = "react-select";
      packageName = "react-select";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-select/-/react-select-3.1.0.tgz";
        sha512 = "wBFVblBH1iuCBprtpyGtd1dGMadsG36W5/t2Aj8OE6WbByDg5jIFyT7X5gT+l0qmT5TqWhxX+VsKJvCEl2uL9g==";
      };
    };
    "react-toastify-5.5.0" = {
      name = "react-toastify";
      packageName = "react-toastify";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-toastify/-/react-toastify-5.5.0.tgz";
        sha512 = "jsVme7jALIFGRyQsri/g4YTsRuaaGI70T6/ikjwZMB4mwTZaCWqj5NqxhGrRStKlJc5npXKKvKeqTiRGQl78LQ==";
      };
    };
    "react-transition-group-1.2.1" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-1.2.1.tgz";
        sha512 = "CWaL3laCmgAFdxdKbhhps+c0HRGF4c+hdM4H23+FI1QBNUyx/AMeIJGWorehPNSaKnQNOAxL7PQmqMu78CDj3Q==";
      };
    };
    "react-transition-group-4.3.0" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-4.3.0.tgz";
        sha512 = "1qRV1ZuVSdxPlPf4O8t7inxUGpdyO5zG9IoNfJxSO0ImU2A1YWkEQvFPuIPZmMLkg5hYs7vv5mMOyfgSkvAwvw==";
      };
    };
    "regenerator-runtime-0.13.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.5.tgz";
        sha512 = "ZS5w8CpKFinUzOwW3c83oPeVXoNsrLsaCoLtJvAClH135j/R77RuymhiSErhm2lKcwSCIpmvIWSbDkIfAqKQlA==";
      };
    };
    "requires-port-1.0.0" = {
      name = "requires-port";
      packageName = "requires-port";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz";
        sha1 = "925d2601d39ac485e091cf0da5c6e694dc3dcaff";
      };
    };
    "resize-observer-polyfill-1.5.1" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.1.tgz";
        sha512 = "LwZrotdHOo12nQuZlHEmtuXdqGoOD0OhaxopaNFxWzInpEgaLWoVuAMbTzixuosCx2nEG58ngzW3vxdWoxIgdg==";
      };
    };
    "resolve-1.15.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.15.1.tgz";
        sha512 = "84oo6ZTtoTUpjgNEr5SJyzQhzL72gaRodsSfyxC/AXRvwu0Yse9H8eF9IpGo7b8YetZhlI6v7ZQ6bKBFV/6S7w==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "resolve-pathname-3.0.0" = {
      name = "resolve-pathname";
      packageName = "resolve-pathname";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pathname/-/resolve-pathname-3.0.0.tgz";
        sha512 = "C7rARubxI8bXFNB/hqcp/4iUeIXJhJZvFPFPiSPRnhU5UPxzMFIl+2E6yY6c4k9giDJAhtV+enfA+G89N6Csng==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "sanitize-html-1.22.1" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.22.1.tgz";
        sha512 = "++IMC00KfMQc45UWZJlhWOlS9eMrME38sFG9GXfR+k6oBo9JXSYQgTOZCl9j3v/smFTRNT9XNwz5DseFdMY+2Q==";
      };
    };
    "scheduler-0.19.1" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz";
        sha512 = "n/zwRWRYSUj0/3g/otKDRPMh6qv2SYMWNq85IEa8iZyAv8od9zDYpGSnpBEjNgcMNq6Scbu5KfIPxNF72R/2EA==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "split-on-first-1.1.0" = {
      name = "split-on-first";
      packageName = "split-on-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-on-first/-/split-on-first-1.1.0.tgz";
        sha512 = "43ZssAJaMusuKWL8sKUBQXHWOpq8d6CfN/u1p4gUzfJkM05C8rxTmYrkIPTXapZpORA6LkkzcUulJ8FqA7Uudw==";
      };
    };
    "srcset-2.0.1" = {
      name = "srcset";
      packageName = "srcset";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/srcset/-/srcset-2.0.1.tgz";
        sha512 = "00kZI87TdRKwt+P8jj8UZxbfp7mK2ufxcIMWvhAOZNJTRROimpHeruWrGvCZneiuVDLqdyHefVp748ECTnyUBQ==";
      };
    };
    "streamsaver-2.0.3" = {
      name = "streamsaver";
      packageName = "streamsaver";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamsaver/-/streamsaver-2.0.3.tgz";
        sha512 = "IpXeZ67YxcsrfZHe3yg/IyZ5KPfRSn1teDy5mRX2e8M6K410NcJNcR+SFQ2Z92DO36VBUArQP4Vy3Qu33MwIOQ==";
      };
    };
    "strict-uri-encode-2.0.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-2.0.0.tgz";
        sha1 = "b9c7330c7042862f6b142dc274bbcc5866ce3546";
      };
    };
    "string-hash-1.1.3" = {
      name = "string-hash";
      packageName = "string-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-hash/-/string-hash-1.1.3.tgz";
        sha1 = "e8aafc0ac1855b4666929ed7dd1275df5d6c811b";
      };
    };
    "substyle-6.3.1" = {
      name = "substyle";
      packageName = "substyle";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/substyle/-/substyle-6.3.1.tgz";
        sha512 = "S25YRgVQB25cLXgGAJ7AXTYewkIB/9Fa1Y7jxkN48U4N6rbK9YhVEiF7vtPGLlJl8ebSOJ3N4t8cd6jL8MH7Uw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-6.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-6.1.0.tgz";
        sha512 = "qe1jfm1Mg7Nq/NSh6XE24gPXROEVsWHxC1LIx//XNlD9iw7YZQGjZNjYN7xGaEG6iKdA8EtNFW6R0gjnVXp+wQ==";
      };
    };
    "tiny-invariant-1.1.0" = {
      name = "tiny-invariant";
      packageName = "tiny-invariant";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-invariant/-/tiny-invariant-1.1.0.tgz";
        sha512 = "ytxQvrb1cPc9WBEI/HSeYYoGD0kWnGEOR8RY6KomWLBVhqz0RgTwVO9dLrGz7dC+nN9llyI7OKAgRq8Vq4ZBSw==";
      };
    };
    "tiny-warning-1.0.3" = {
      name = "tiny-warning";
      packageName = "tiny-warning";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-warning/-/tiny-warning-1.0.3.tgz";
        sha512 = "lBN9zLN/oAf68o3zNXYrdCt1kP8WsiGW8Oo2ka41b2IM5JL/S1CTyX1rW0mb/zSuJun0ZUrDxx4sqvYS2FWzPA==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha1 = "dc5e698cbd079265bc73e0377681a4e4e83f616e";
      };
    };
    "uncontrollable-7.1.1" = {
      name = "uncontrollable";
      packageName = "uncontrollable";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uncontrollable/-/uncontrollable-7.1.1.tgz";
        sha512 = "EcPYhot3uWTS3w00R32R2+vS8Vr53tttrvMj/yA1uYRhf8hbTG2GyugGqWDY0qIskxn0uTTojVd6wPYW9ZEf8Q==";
      };
    };
    "underscore-1.9.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.2.tgz";
        sha512 = "D39qtimx0c1fI3ya1Lnhk3E9nONswSKhnffBI0gME9C99fYOkNi04xs8K6pePLhvl1frbDemkaBQ5ikWllR2HQ==";
      };
    };
    "url-parse-1.4.7" = {
      name = "url-parse";
      packageName = "url-parse";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse/-/url-parse-1.4.7.tgz";
        sha512 = "d3uaVyzDB9tQoSXFvuSUNFibTd9zxd2bkVrDRvF5TmvWWQwqE4lgYJ5m+x1DbecWkw+LK4RNl2CU1hHuOKPVlg==";
      };
    };
    "url-toolkit-2.1.6" = {
      name = "url-toolkit";
      packageName = "url-toolkit";
      version = "2.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-toolkit/-/url-toolkit-2.1.6.tgz";
        sha512 = "UaZ2+50am4HwrV2crR/JAf63Q4VvPYphe63WGeoJxeu8gmOm0qxPt+KsukfakPNrX9aymGNEkkaoICwn+OuvBw==";
      };
    };
    "utf8-3.0.0" = {
      name = "utf8";
      packageName = "utf8";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8/-/utf8-3.0.0.tgz";
        sha512 = "E8VjFIQ/TyQgp+TZfS6l8yp/xWppSAHzidGiRrqe4bK4XP9pTRyKFgGJpO3SN7zdX4DeomTrwaseCHovfpFcqQ==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "value-equal-1.0.1" = {
      name = "value-equal";
      packageName = "value-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/value-equal/-/value-equal-1.0.1.tgz";
        sha512 = "NOJ6JZCAWr0zlxZt+xqCHNTEKOsrks2HQd4MqhP1qy4z1SkbEP467eNx6TgDKXMvUOb+OENfJCZwM+16n7fRfw==";
      };
    };
    "vcard-parser-1.0.0" = {
      name = "vcard-parser";
      packageName = "vcard-parser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vcard-parser/-/vcard-parser-1.0.0.tgz";
        sha512 = "rSEjrjBK3of4VimMR5vBjLLcN5ZCSp9yuVzyx5i4Fwx74Yd0s+DnHtSit/wAAtj1a7/T/qQc0ykwXADoD0+fTQ==";
      };
    };
    "warning-2.1.0" = {
      name = "warning";
      packageName = "warning";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-2.1.0.tgz";
        sha1 = "21220d9c63afc77a8c92111e011af705ce0c6901";
      };
    };
    "warning-3.0.0" = {
      name = "warning";
      packageName = "warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-3.0.0.tgz";
        sha1 = "32e5377cb572de4ab04753bdf8821c01ed605b7c";
      };
    };
    "warning-4.0.3" = {
      name = "warning";
      packageName = "warning";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-4.0.3.tgz";
        sha512 = "rpJyN222KWIvHJ/F53XSZv0Zl/accqHR8et1kpaMTD/fLCRxtV8iX8czMzY7sVZupTI3zcUTg8eycS2kNF9l6w==";
      };
    };
    "web-streams-polyfill-1.3.2" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-1.3.2.tgz";
        sha1 = "3719245e909282d93967825f44bcd550e9c03995";
      };
    };
    "webpack-merge-4.2.2" = {
      name = "webpack-merge";
      packageName = "webpack-merge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/webpack-merge/-/webpack-merge-4.2.2.tgz";
        sha512 = "TUE1UGoTX2Cd42j3krGYqObZbOD+xF7u28WB7tfUordytSjbWTIjK/8V0amkBfTYN4/pB/GIDlJZZ657BGG19g==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
    "yaml-1.8.3" = {
      name = "yaml";
      packageName = "yaml";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-1.8.3.tgz";
        sha512 = "X/v7VDnK+sxbQ2Imq4Jt2PRUsRsP7UcpSl3Llg6+NRRqWLIvxkMFYtH1FmvwNGYRKKPa+EPA4qDBlI9WVG1UKw==";
      };
    };
  };
  args = {
    name = "intrustd-photo-app";
    packageName = "intrustd-photo-app";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@babel/code-frame-7.8.3"
      sources."@babel/helper-module-imports-7.8.3"
      sources."@babel/helper-validator-identifier-7.9.0"
      sources."@babel/highlight-7.9.0"
      sources."@babel/runtime-7.9.2"
      sources."@babel/types-7.9.0"
      sources."@emotion/cache-10.0.29"
      sources."@emotion/core-10.0.28"
      sources."@emotion/css-10.0.27"
      sources."@emotion/hash-0.8.0"
      sources."@emotion/memoize-0.7.4"
      sources."@emotion/serialize-0.11.16"
      sources."@emotion/sheet-0.9.4"
      sources."@emotion/stylis-0.8.5"
      sources."@emotion/unitless-0.7.5"
      sources."@emotion/utils-0.11.3"
      sources."@emotion/weak-memoize-0.2.5"
      sources."@fortawesome/fontawesome-free-5.13.0"
      sources."@popperjs/core-2.1.1"
      sources."@restart/context-2.1.4"
      sources."@restart/hooks-0.3.22"
      sources."@types/parse-json-4.0.0"
      sources."@types/prop-types-15.7.3"
      sources."@types/react-16.9.27"
      sources."@wojtekmaj/date-utils-1.0.2"
      sources."ansi-styles-3.2.1"
      sources."array-move-2.2.1"
      sources."babel-plugin-emotion-10.0.29"
      sources."babel-plugin-macros-2.8.0"
      sources."babel-plugin-syntax-jsx-6.18.0"
      sources."base64-js-1.3.1"
      sources."blacklist-1.1.4"
      sources."bootstrap-4.4.1"
      sources."buffer-5.5.0"
      sources."cache-polyfill-1.0.1"
      sources."callsites-3.1.0"
      sources."chain-function-1.0.1"
      sources."chalk-2.4.2"
      sources."chrono-node-1.4.4"
      sources."classnames-2.2.6"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."convert-source-map-1.7.0"
      sources."cosmiconfig-6.0.0"
      sources."csstype-2.6.9"
      sources."dayjs-1.8.23"
      sources."decode-uri-component-0.2.0"
      sources."dexie-2.0.4"
      sources."dom-helpers-3.4.0"
      sources."dom-serializer-0.2.2"
      sources."domelementtype-2.0.1"
      sources."domhandler-3.0.0"
      sources."domutils-2.0.0"
      sources."entities-2.0.0"
      sources."error-ex-1.3.2"
      sources."escape-string-regexp-1.0.5"
      sources."event-target-shim-5.0.1"
      sources."eventemitter3-3.1.0"
      sources."find-root-1.1.0"
      sources."fingertree-js-1.0.2"
      sources."get-user-locale-1.3.0"
      sources."has-flag-3.0.0"
      sources."history-4.10.1"
      sources."hls.js-0.12.4"
      sources."hoist-non-react-statics-3.3.2"
      sources."htmlparser2-4.1.0"
      sources."http-parser-js-0.4.13"
      sources."ieee754-1.1.13"
      sources."immutable-3.8.2"
      sources."import-fresh-3.2.1"
      (sources."intrustd-../../../js" // {
        dependencies = [
          sources."event-target-shim-3.0.2"
        ];
      })
      sources."invariant-2.2.4"
      sources."is-arrayish-0.2.1"
      sources."isarray-0.0.1"
      sources."jquery-3.4.1"
      sources."js-tokens-4.0.0"
      sources."json-parse-better-errors-1.0.2"
      sources."lines-and-columns-1.1.6"
      sources."lodash-4.17.15"
      sources."lodash-es-4.17.15"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.escaperegexp-4.1.2"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.mergewith-4.6.2"
      sources."lodash.once-4.1.1"
      sources."loose-envify-1.4.0"
      sources."lru-cache-5.1.1"
      sources."medium-editor-5.23.3"
      sources."memoize-one-5.1.1"
      sources."merge-class-names-1.3.0"
      sources."mithril-1.1.7"
      sources."moment-2.24.0"
      sources."nprogress-0.2.0"
      sources."object-assign-4.1.1"
      sources."parent-module-1.0.1"
      sources."parse-json-5.0.0"
      sources."path-parse-1.0.6"
      sources."path-to-regexp-1.8.0"
      sources."path-type-4.0.0"
      sources."popper.js-1.16.1"
      (sources."postcss-7.0.27" // {
        dependencies = [
          sources."source-map-0.6.1"
          sources."supports-color-6.1.0"
        ];
      })
      sources."prop-types-15.7.2"
      (sources."prop-types-extra-1.1.1" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      sources."query-string-6.11.1"
      sources."querystringify-2.1.1"
      sources."raf-schd-4.0.2"
      sources."react-16.13.1"
      sources."react-addons-css-transition-group-15.6.2"
      (sources."react-bootstrap-1.0.0" // {
        dependencies = [
          sources."dom-helpers-5.1.3"
          sources."react-transition-group-4.3.0"
          sources."warning-4.0.3"
        ];
      })
      sources."react-calendar-3.0.1"
      sources."react-dom-16.13.1"
      sources."react-draggable-4.2.0"
      sources."react-input-autosize-2.2.2"
      sources."react-is-16.13.1"
      sources."react-lifecycles-compat-3.0.4"
      sources."react-medium-editor-1.8.1"
      sources."react-mentions-2.4.2"
      sources."react-moment-0.9.7"
      (sources."react-overlays-3.0.1" // {
        dependencies = [
          sources."dom-helpers-5.1.3"
          sources."warning-4.0.3"
        ];
      })
      sources."react-resize-detector-4.2.1"
      (sources."react-router-4.3.1" // {
        dependencies = [
          sources."hoist-non-react-statics-2.5.5"
          sources."warning-4.0.3"
        ];
      })
      (sources."react-router-dom-4.3.1" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      (sources."react-select-3.1.0" // {
        dependencies = [
          sources."dom-helpers-5.1.3"
          sources."react-transition-group-4.3.0"
        ];
      })
      (sources."react-toastify-5.5.0" // {
        dependencies = [
          sources."dom-helpers-5.1.3"
          sources."react-transition-group-4.3.0"
        ];
      })
      sources."react-transition-group-1.2.1"
      sources."regenerator-runtime-0.13.5"
      sources."requires-port-1.0.0"
      sources."resize-observer-polyfill-1.5.1"
      sources."resolve-1.15.1"
      sources."resolve-from-4.0.0"
      sources."resolve-pathname-3.0.0"
      sources."safe-buffer-5.1.2"
      sources."sanitize-html-1.22.1"
      sources."scheduler-0.19.1"
      sources."source-map-0.5.7"
      sources."split-on-first-1.1.0"
      sources."srcset-2.0.1"
      sources."streamsaver-2.0.3"
      sources."strict-uri-encode-2.0.0"
      sources."string-hash-1.1.3"
      (sources."substyle-6.3.1" // {
        dependencies = [
          sources."warning-2.1.0"
        ];
      })
      sources."supports-color-5.5.0"
      sources."tiny-invariant-1.1.0"
      sources."tiny-warning-1.0.3"
      sources."to-fast-properties-2.0.0"
      sources."uncontrollable-7.1.1"
      sources."underscore-1.9.2"
      sources."url-parse-1.4.7"
      sources."url-toolkit-2.1.6"
      sources."utf8-3.0.0"
      sources."uuid-3.4.0"
      sources."value-equal-1.0.1"
      sources."vcard-parser-1.0.0"
      sources."warning-3.0.0"
      sources."web-streams-polyfill-1.3.2"
      sources."webpack-merge-4.2.2"
      sources."xtend-4.0.2"
      sources."yallist-3.1.1"
      sources."yaml-1.8.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The default Photos application that ships with intrustd";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}